import Link from 'next/link';
import { SiteHeader, SiteFooter } from '@/components/site-shell';
import { Icon, type IconName } from '@/components/icon';
import { CampusArt } from '@/components/campus-art';
const streams: {name:string; icon:IconName; text:string; color:string}[] = [
 {name:'Food',icon:'leaf',text:'Less surplus. More purpose.',color:'green'},
 {name:'Water',icon:'water',text:'Every drop, a second chance.',color:'blue'},
 {name:'Energy',icon:'sun',text:'Make the most of your sunshine.',color:'gold'},
 {name:'Materials',icon:'recycle',text:'The next life starts here.',color:'purple'}
];
export default function Home() { return <><SiteHeader/><main id="main">
 <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="tiny-dot"/> CIRCULARITY STARTS WITH YOUR COMMUNITY</div><h1>Less waste.<br/>More <span className="serif accent">possibility.</span></h1><p className="hero-description">Predict surplus. Put resources to better use.<br/>One connected platform for the food, water, energy, and materials that keep your community moving.</p><div className="hero-actions"><Link className="button button-dark" href="/demo">Explore the demo <Icon name="arrow"/></Link><Link className="button button-outline" href="/how-it-works"><span className="play-symbol">▷</span> See how it works</Link></div><p className="hero-footnote"><Icon name="building" size={15}/> Built around campuses, societies & communities</p></div>
 <div className="hero-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-label"><span className="tiny-dot"/> A BETTER KIND OF FULL CIRCLE</div><CampusArt/><div className="floating-card solar-card"><span className="icon-tile gold"><Icon name="sun"/></span><div><strong>Powered by possibility</strong><span>Solar energy → everyday use</span></div></div><div className="floating-card garden-card"><span className="icon-tile green"><Icon name="leaf"/></span><div><strong>Nothing good goes to waste</strong><span>Food scraps → thriving gardens</span></div><span className="mini-check"><Icon name="check" size={13}/></span></div><div className="art-caption">An illustration of a connected campus</div></div>
 </section>
 <section className="stream-strip wrap" aria-label="Four resource streams">{streams.map(s=><Link key={s.name} href={`/demo?view=${s.name.toLowerCase()}`}><span className={`icon-tile ${s.color}`}><Icon name={s.icon} size={24}/></span><span><strong>{s.name}</strong><small>{s.text}</small></span><Icon name="arrow" size={17}/></Link>)}</section>
 <section className="loop-section wrap" id="loop"><div className="section-heading"><div><p className="eyebrow">SMALL ACTIONS. CONNECTED IMPACT.</p><h2>A smarter way to <span className="serif">close the loop.</span></h2></div><p>From your first measurement to a resource’s next life.<br/>See the whole picture, then take the right next step.</p></div><div className="workflow-grid">{[
  ['01','sensor','Connect & measure','Bring together IoT readings and manual data from your bins, buildings, cafeteria, and gardens.'],
  ['02','spark','Predict & understand','Turn resource patterns into baseline forecasts and clear, explainable recommendations.'],
  ['03','recycle','Prevent, reuse, route','Your team reviews the next best use: reduce surplus, reuse locally, or plan a verified handoff.'],
  ['04','chart','Track & grow','Follow actual results, trace resource passports, and recognise verified contributions with GreenPoints.']
 ].map(([n,icon,title,text])=><article key={n} className="workflow-card"><div className="step-top"><Icon name={icon as IconName} size={26}/><span>{n}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div><Link href="/how-it-works" className="text-link">Explore the EcoLoop workflow <Icon name="arrow" size={18}/></Link></section>
 <section className="workspace-section wrap"><div className="workspace-copy"><p className="eyebrow">ONE SHARED WORKSPACE</p><h2>Your community.<br/>All its potential.</h2><p>Less guesswork for the people making a difference. Bring every resource stream into focus, with practical next steps and the evidence behind them.</p><ul className="check-list"><li><Icon name="check"/> Four streams, one clear overview</li><li><Icon name="check"/> Recommendations your team controls</li><li><Icon name="check"/> Traceable handoffs and transparent rewards</li></ul><Link href="/demo" className="button button-dark">Take a look inside <Icon name="arrow"/></Link></div><div className="dashboard-preview"><div className="preview-top"><span><Icon name="grid" size={17}/> Campus overview</span><span className="badge">Simulated demo</span></div><div className="preview-message"><span className="icon-tile green"><Icon name="spark"/></span><div><strong>A little planning. A lot of possibility.</strong><p>Your next resource loop starts with a measurement.</p></div></div><div className="preview-metrics">{streams.map(s=><div key={s.name}><Icon name={s.icon}/><strong>{s.name}</strong><span>Connected thinking</span></div>)}</div><div className="preview-flow"><span>Cafeteria</span><Icon name="arrow"/><span>Compost</span><Icon name="arrow"/><span>Campus garden</span></div><p>Illustrative resource loop · human review at every step</p></div></section>
 <section className="pilot-banner wrap"><div><p className="eyebrow">BIG CHANGE CAN START SMALL</p><h2>One site. One resource.<br/><span className="serif">A better tomorrow.</span></h2><p>Explore what a supervised EcoLoop pilot could look like for your community.</p></div><Link className="button button-lime" href="/pilot">Plan your pilot <Icon name="arrow"/></Link><div className="banner-rings" aria-hidden="true"/></section>
 </main><SiteFooter/></>; }
