'use client';
import Link from 'next/link';
import {useEffect, useRef, useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Brand} from './brand';
import {Icon, type IconName} from './icon';
import {readings, recommendations, passports, streamInfo, type Stream, type DemoSite} from '@/lib/demo-data';
import {csvCell, sumQuantities} from '../../../../packages/domain/src/quantities';
const navItems: {id:string;label:string;icon:IconName;count?:string}[] = [
 {id:'overview',label:'Overview',icon:'grid'}, {id:'autopilot',label:'Circularity engine',icon:'spark',count:'3'},
 {id:'resources',label:'Resource passports',icon:'box'}, {id:'points',label:'GreenPoints',icon:'award'},
 {id:'hub',label:'Connected hub',icon:'sensor'}, {id:'reports',label:'Reports',icon:'chart'}
];
const validViews=['overview','autopilot','resources','points','hub','reports','notifications','food','water','energy','materials'];
const formatter=new Intl.NumberFormat('en-IN',{maximumFractionDigits:1});
type Detail={title:string;eyebrow:string;body:React.ReactNode};
export function Dashboard(){
 const searchParams=useSearchParams();
 const queryView=searchParams.get('view') || 'overview';
 const view=validViews.includes(queryView)?queryView:'overview';
 const site:DemoSite=searchParams.get('site')==='community'?'community':'campus';
 const period=searchParams.get('period')==='day'?'day':'week';
 const [stream,setStream]=useState<Stream>('food');
 const [tableView,setTableView]=useState(false);
 const [query,setQuery]=useState('');
 const [filter,setFilter]=useState('All resources');
 const [detail,setDetail]=useState<Detail|null>(null);
 const [menuOpen,setMenuOpen]=useState(false);
 const [mobile,setMobile]=useState(false);
 const [ready,setReady]=useState(false);
 const sidebarRef=useRef<HTMLElement>(null);
 const menuTrigger=useRef<HTMLButtonElement>(null);
 const [notice,setNotice]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 const trigger=useRef<HTMLElement|null>(null);
 const heading=useRef<HTMLHeadingElement>(null);
 const initialRoute=useRef(true);
 const isStream=(['food','water','energy','materials'] as string[]).includes(view);
 const activeStream=isStream?view as Stream:stream;
 const siteName=site==='campus'?'Demo Campus':'Demo Community';
 const rows=readings.slice(period==='day'?-1:0).map(r=>site==='community'?{...r,water:String(Number(r.water)/2),materials:String(Number(r.materials)/2)}:r);
 const available=(s:Stream)=>site==='campus'||(s!=='food'&&s!=='energy');
 const total=(s:Stream)=>formatter.format(Number(sumQuantities(rows.map(r=>r[s]))));
 const periodLabel=period==='day'?'28 September 2026':'22–28 September 2026';
 const selectedRecommendations=recommendations.filter(r=>(site==='campus'||r.stream==='water')&&(!isStream||r.stream===view));
 const title=isStream?`${streamInfo[view as Stream].label} overview`:view==='overview'?'A good day to close the loop.':view==='autopilot'?'Your next best actions.':view==='resources'?'Every resource has a story.':view==='points'?'Good actions, recognised.':view==='hub'?'Your connected campus.':view==='reports'?'A clearer picture of your resources.':'Stay in the loop.';
 function url(nextView:string, nextSite=site, nextPeriod=period){return `/demo?view=${nextView}&site=${nextSite}&period=${nextPeriod}`}
 function openDetail(next:Detail){trigger.current=document.activeElement as HTMLElement;setDetail(next)}
 useEffect(()=>{if(detail&&!dialog.current?.open)dialog.current?.showModal();},[detail]);
 useEffect(()=>{setReady(true)},[]);
 useEffect(()=>{const media=window.matchMedia('(max-width: 767px)');const update=()=>{setMobile(media.matches);if(!media.matches)setMenuOpen(false)};update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 useEffect(()=>{if(!menuOpen)return;const previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';const closeButton=sidebarRef.current?.querySelector<HTMLButtonElement>('button');closeButton?.focus();const trap=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenuOpen(false);return}if(event.key!=='Tab')return;const items=Array.from(sidebarRef.current?.querySelectorAll<HTMLElement>('a[href],button')??[]).filter(el=>el.offsetParent!==null);const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}};document.addEventListener('keydown',trap);return()=>{document.body.style.overflow=previousOverflow;document.removeEventListener('keydown',trap);menuTrigger.current?.focus()}},[menuOpen]);
 useEffect(()=>{setMenuOpen(false);setQuery('');setFilter('All resources');setStream(site==='community'?'water':'food');setNotice('');if(initialRoute.current)initialRoute.current=false;else heading.current?.focus();},[view,site,siteName]);
 function closeDetail(){dialog.current?.close();setDetail(null);trigger.current?.focus()}
 function explainRecommendation(id:string){const r=recommendations.find(r=>r.id===id)!;openDetail({title:r.title,eyebrow:`${r.kind} · ${r.status} · simulated`,body:<><p className="detail-lead">{r.description}</p><div className="detail-stat">{r.quantity} <span>{r.unit}</span><small>{r.stream==='food'?'Estimated reduction in initial preparation':r.status==='Blocked'?'Quantity unavailable':'Proposed handoff quantity'}</small></div><h3>Why this recommendation?</h3><ul className="reason-list">{r.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><div className="note-box"><Icon name="info"/><p>{r.limitation}</p></div><dl className="detail-meta"><div><dt>Responsible role</dt><dd>{r.assignee}</dd></div><div><dt>Input snapshot</dt><dd>28 Sep 2026, 12:00 IST · simulated</dd></div><div><dt>Decision model</dt><dd>Deterministic rules · v1</dd></div></dl><p className="read-only-note">Read-only demo. Review → human approval → operator action → evidence. Approval does not mean completion.</p></>})}
 function exportReport(){const header=['site','date','metric','quantity','unit','basis','source'];const data=rows.flatMap(r=>(Object.keys(streamInfo) as Stream[]).filter(available).map(s=>[siteName,r.date,streamInfo[s].metric,r[s],streamInfo[s].unit,'simulated',streamInfo[s].source]));const csv=[header,...data].map(row=>row.map(csvCell).join(',')).join('\r\n');const blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8;'});const link=document.createElement('a');const downloadUrl=URL.createObjectURL(blob);link.href=downloadUrl;link.download=`ecoloop-${site}-${period}-SIMULATED.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(downloadUrl),1000);setNotice('Simulated report downloaded. It includes only the selected site and reporting period.');}
 function chart(){const info=streamInfo[activeStream];const vals=rows.map(r=>Number(r[activeStream]));const max=Math.max(...vals,1)*1.2;const points=vals.map((v,i)=>`${rows.length===1?300:50+i*550/(rows.length-1)},${185-v/max*150}`).join(' ');return <section className="panel trend-panel"><div className="panel-heading"><div><h2>Resource trends</h2><p>{info.metric} · {info.unit} · simulated</p></div><button className="text-button" onClick={()=>setTableView(!tableView)}>{tableView?'Show chart':'View data table'} <Icon name={tableView?'chart':'grid'} size={15}/></button></div>{!isStream&&<div className="stream-tabs" aria-label="Resource trend selection">{(Object.keys(streamInfo) as Stream[]).map(s=><button key={s} aria-pressed={activeStream===s} onClick={()=>setStream(s)} className={activeStream===s?'selected':''}><Icon name={streamInfo[s].icon} size={15}/>{streamInfo[s].label}</button>)}</div>}{!available(activeStream)?<div className="empty-state"><Icon name="sensor" size={32}/><h3>This module is not configured.</h3><p>{siteName} has no {info.label.toLowerCase()} readings in this demo.</p></div>:tableView?<div className="table-scroll" tabIndex={0} role="region" aria-label="Trend data"><table><caption>{info.metric} ({info.unit}) · {periodLabel} · simulated</caption><thead><tr><th scope="col">Date</th><th scope="col">Quantity ({info.unit})</th><th scope="col">Basis</th></tr></thead><tbody>{rows.map(r=><tr key={r.date}><td>{r.date}</td><td>{formatter.format(Number(r[activeStream]))}</td><td>Simulated</td></tr>)}</tbody></table></div>:<div className={`chart-wrap chart-${info.color}`}><svg viewBox="0 0 640 230" role="img" aria-label={`${info.metric}, simulated. ${rows.length} daily observations, total ${total(activeStream)} ${info.unit}. Equivalent values available in View data table.`}><defs><linearGradient id="chart-fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="currentColor" stopOpacity=".16"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(i=><g key={i}><line x1="50" x2="604" y1={35+i*50} y2={35+i*50} stroke="#e5e9e1" strokeDasharray="3 5"/><text x="38" y={39+i*50} textAnchor="end" fill="#737c70" fontSize="10">{formatter.format(max*(3-i)/3)}</text></g>)}{rows.length>1&&<><polygon points={`50,185 ${points} 600,185`} fill="url(#chart-fill)"/><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round"/></>}{vals.map((v,i)=><g key={i}><circle cx={rows.length===1?300:50+i*550/(rows.length-1)} cy={185-v/max*150} r="4" fill="white" stroke="currentColor" strokeWidth="2"/><text x={rows.length===1?300:50+i*550/(rows.length-1)} y="212" textAnchor="middle" fontSize="10" fill="#737c70">{rows[i].date.slice(8)} Sep</text></g>)}</svg><div className="chart-legend"><span className="legend-dot"/>{info.metric}<span>Simulated observations · not a forecast</span></div></div>}</section>}
 function recommendationCards(){return <section className="recommendations-section"><div className="section-inline"><div><h2>Small steps. Better loops.</h2><p>Explainable recommendations, with your team in control.</p></div>{view!=='autopilot'&&<Link href={url('autopilot')} className="text-link">View all actions <Icon name="arrow" size={16}/></Link>}</div><div className="recommendation-grid">{selectedRecommendations.length?selectedRecommendations.map(r=><article className="recommendation-card" key={r.id}><div className="rec-top"><span className={`pill ${streamInfo[r.stream].color}`}><Icon name={streamInfo[r.stream].icon} size={14}/>{r.kind}</span><span className={`status-label ${r.status==='Blocked'?'warning':''}`}>{r.status}</span></div><h3>{r.title}</h3><p>{r.description}</p><div className="rec-bottom"><span>{r.quantity!=='—'&&<><strong>{r.quantity}</strong> {r.unit}</>}{r.quantity==='—'&&'Evidence needed'}<small>{r.stream==='food'?'Estimated plan reduction':r.stream==='materials'?'Proposed quantity':'Quality review expired'}</small></span><button className="round-button" aria-label={`View recommendation: ${r.title}`} onClick={()=>explainRecommendation(r.id)}><Icon name="arrow" size={18}/></button></div></article>):<div className="panel empty-state"><Icon name="spark"/><h3>No recommendations for this stream.</h3><p>Solar generation alone does not establish an actionable scheduling opportunity.</p></div>}</div></section>}
 function resources(){const filtered=passports.filter(p=>(filter==='All resources'||p.type===filter)&&`${p.code} ${p.name}`.toLowerCase().includes(query.toLowerCase()));return <section className="panel"><div className="panel-heading"><div><h2>Resource passports</h2><p>Illustrative campus batches · provenance from measurement to receipt</p></div><span className="badge">{site==='campus'?'3':'0'} passports</span></div>{site==='community'?<div className="empty-state"><Icon name="box" size={36}/><h3>No resource passports yet</h3><p>This demo community has aggregate readings only. Choose Demo Campus to explore batch histories.</p></div>:<><div className="table-toolbar"><label className="search-field"><Icon name="search" size={18}/><span className="sr-only">Search passports</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search resource or passport…"/></label><label><span className="sr-only">Filter resource type</span><select aria-label="Filter resource type" value={filter} onChange={e=>setFilter(e.target.value)}>{['All resources','Compost','Cardboard','Paper'].map(t=><option key={t}>{t}</option>)}</select></label></div><div className="table-scroll" tabIndex={0} role="region" aria-label="Resource passport list"><table><thead><tr><th scope="col">Resource</th><th scope="col">Passport</th><th scope="col">Quantity</th><th scope="col">Status</th><th scope="col"><span className="sr-only">Details</span></th></tr></thead><tbody>{filtered.map(p=><tr key={p.code}><td><strong>{p.name}</strong><small>{p.source}</small></td><td className="mono">{p.code}</td><td>{p.quantity} {p.unit}</td><td><span className={`pill ${p.status==='Received'?'green':p.status==='Available'?'blue':'gold'}`}>{p.status}</span></td><td><button className="round-button" aria-label={`Open passport ${p.code}`} onClick={()=>openDetail({title:p.name,eyebrow:`${p.code} · simulated resource passport`,body:<><div className="detail-stat">{p.quantity} <span>{p.unit}</span><small>Original measured batch quantity · simulated</small></div><div className="timeline">{p.events.map(([date,title,text])=><article key={title}><span className="timeline-dot"/><small>{date} IST · 2026</small><h3>{title}</h3><p>{text}</p></article>)}</div><p className="read-only-note">Demo reference only. This passport is not proof of ownership, real quality approval, or a real-world handoff.</p></>})}><Icon name="chevron" size={16}/></button></td></tr>)}</tbody></table>{filtered.length===0&&<div className="empty-state"><h3>No matching resources</h3><p>Try a different name, passport code, or resource type.</p><button className="button button-outline" onClick={()=>{setQuery('');setFilter('All resources')}}>Clear filters</button></div>}</div></>}</section>}
 return <div className="dashboard" data-ready={ready}><aside ref={sidebarRef} inert={mobile && !menuOpen} className={`sidebar ${menuOpen?'sidebar-open':''}`} aria-label="Workspace sidebar"><div className="sidebar-brand"><Brand/><button className="icon-button mobile-only" aria-label="Close navigation" onClick={()=>setMenuOpen(false)}><Icon name="close"/></button></div><div className="workspace-label">YOUR WORKSPACE <span>DEMO</span></div><div className="site-identity"><span className="site-avatar"><Icon name="building"/></span><div><strong>{siteName}</strong><span>Asia/Kolkata · India</span></div></div><nav aria-label="Workspace navigation">{navItems.map(item=><Link href={url(item.id)} key={item.id} className={view===item.id?'active':''} aria-current={view===item.id?'page':undefined}><Icon name={item.icon} size={19}/><span>{item.label}</span>{item.count&&<small>{site==='campus'?item.count:'1'}</small>}</Link>)}<p className="nav-label">RESOURCE STREAMS</p>{(Object.keys(streamInfo) as Stream[]).map(s=><Link key={s} href={url(s)} className={view===s?'active':''} aria-current={view===s?'page':undefined}><Icon name={streamInfo[s].icon} size={19}/><span>{streamInfo[s].label}</span></Link>)}</nav><div className="sidebar-bottom"><div className="sidebar-pilot"><Icon name="leaf" size={25}/><strong>Make your own loop.</strong><p>Bring EcoLoop to your community.</p><Link href="/pilot">Explore the pilot <Icon name="arrow" size={16}/></Link></div><Link className="back-home" href="/">← Back to EcoLoop</Link><div className="demo-profile"><div>DC</div><span><strong>Demo explorer</strong><small>Read-only workspace</small></span><Icon name="info" size={17}/></div></div></aside>{menuOpen&&<button className="nav-backdrop" aria-label="Close navigation" onClick={()=>setMenuOpen(false)}/>}
 <div className="workspace-main" inert={mobile && menuOpen}><header className="workspace-header"><div className="breadcrumb"><button ref={menuTrigger} className="icon-button mobile-only" aria-label="Open navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}><Icon name="menu"/></button><span>Workspace</span><Icon name="chevron" size={12}/><strong>{isStream?streamInfo[view as Stream].label:navItems.find(n=>n.id===view)?.label||'Notifications'}</strong></div><div className="workspace-header-right"><span className="demo-mode"><span className="tiny-dot"/> Demo workspace</span><Link className="notification-button" aria-label="View 2 demo alerts" href={url('notifications')}><Icon name="bell"/><span/></Link><div className="avatar">DC</div></div></header><div className="demo-banner"><Icon name="info" size={15}/><span><strong>Demo</strong> · All readings, partners, and rewards shown here are simulated.</span><Link href="/how-it-works">How EcoLoop works <Icon name="external" size={13}/></Link></div>
 <main id="main" className="dashboard-content"><div className="dashboard-title"><div><p className="eyebrow">{siteName.toUpperCase()} / {view==='overview'?'RESOURCE OVERVIEW':'SIMULATED WORKSPACE'}</p><h1 ref={heading} tabIndex={-1}>{title}</h1><p>{view==='overview'?'See the bigger picture. Make the next small difference.':'Explore how a connected community could put resources to better use.'}</p></div><button className="button button-white" aria-label="Export simulated report" onClick={exportReport}><Icon name="download" size={16}/> Export report</button></div><div className="dashboard-filters"><div><label><Icon name="building" size={15}/><span className="sr-only">Select site</span><select aria-label="Select site" value={site} onChange={e=>{window.location.href=url('overview',e.target.value as DemoSite,'week')}}><option value="campus">Demo Campus</option><option value="community">Demo Community</option></select></label><label><Icon name="clock" size={15}/><span className="sr-only">Reporting period</span><select aria-label="Reporting period" value={period} onChange={e=>{window.history.pushState(null,'',url(view,site,e.target.value))}}><option value="week">22–28 Sep 2026</option><option value="day">28 Sep 2026</option></select></label></div><span className="snapshot-label"><span className="tiny-dot"/> Snapshot: 28 Sep, 12:00 IST</span></div><p className="live-notice" role="status">{notice}</p>
 {(view==='overview'||isStream||view==='reports')&&<><div className={`metrics-grid ${isStream?'single-metric':''}`}>{(isStream?[view as Stream]:Object.keys(streamInfo) as Stream[]).map(s=><Link href={url(s)} className={`metric-card metric-${streamInfo[s].color}`} key={s}><div className="metric-top"><span className={`icon-tile ${streamInfo[s].color}`}><Icon name={streamInfo[s].icon} size={19}/></span><span className="basis-label">SIMULATED</span><Icon name="external" size={14}/></div><p>{streamInfo[s].metric}</p><div className="metric-value">{available(s)?total(s):'—'} <span>{available(s)?streamInfo[s].unit:''}</span></div><div className="metric-footer">{available(s)?<><span className="tiny-dot"/>{period==='day'?'Daily reading':'7-day total'} · {streamInfo[s].source}</>:'Module not configured'}</div></Link>)}</div><div className="overview-middle">{chart()}<section className="loop-impact-panel"><div className="panel-heading"><h2>The bigger picture</h2><Icon name="leaf" size={21}/></div><div className="loop-ring"><div><Icon name="recycle" size={38}/><strong>4 streams.</strong><span>One connected community.</span></div></div><div className="impact-caption"><strong>Every resource has a next chapter.</strong><p>Measure each stream in its own unit. Review recommendations before taking action.</p></div><Link href="/how-it-works">See how the loop connects <Icon name="arrow" size={16}/></Link></section></div></>}
 {(view==='overview'||isStream||view==='autopilot')&&recommendationCards()}
 {(view==='resources'||view==='overview')&&<div className="section-space">{resources()}</div>}
 {view==='points'&&<div className="points-layout"><section className="points-hero"><span className="icon-tile green"><Icon name="award" size={28}/></span><p>YOUR DEMO GREENPOINTS</p><h2>{site==='campus'?'30':'—'} <span>points</span></h2><p>{site==='campus'?'One verified contribution in this fictional example.':'No contributions have been seeded for this community.'}</p><div>Recognition for verified actions.<br/>GreenPoints have no cash value.</div></section><section className="panel"><h2>Understand every point.</h2><p className="muted">Demo policy v1 · cardboard · 100 points per member/site/local day</p>{site==='campus'?<><div className="points-formula"><span><strong>10 kg</strong>Verified quantity</span><b>×</b><span><strong>2</strong>Points per kg</span><b>×</b><span><strong>1.50</strong>Multiplier</span><b>=</b><span><strong>30</strong>Points awarded</span></div><div className="ledger-row"><span className="icon-tile green"><Icon name="recycle"/></span><div><strong>Cardboard contribution</strong><small>28 Sep 2026 · independently verified · simulated</small></div><strong>+30</strong></div></>:<div className="empty-state"><h3>No GreenPoints entries yet.</h3><p>Choose Demo Campus to inspect an illustrative award.</p></div>}<p className="read-only-note">The production design awards points server-side only after independent verification. Daily caps apply; self-verification is prohibited. Corrections append a reversal rather than editing an award.</p></section></div>}
 {view==='hub'&&<section className="panel"><div className="panel-heading"><div><h2>Modules & measurement points</h2><p>Simulated registry · sensor state is evaluated against the fixed demo snapshot</p></div><span className="badge">No connected hardware</span></div><div className="hub-grid">{[{name:'Cafeteria weighing',icon:'leaf',state:site==='campus'?'Manual input':'Not configured',text:'Daily food waste · kg'},{name:'Garden reuse meter',icon:'water',state:'Simulated reading',text:'Last observed 28 Sep, 11:55 IST'},{name:'Rooftop solar',icon:'sun',state:site==='campus'?'Simulated reading':'Not configured',text:'Daily generation · kWh'},{name:'Garden soil sensor',icon:'sensor',state:'Stale',text:'Last observed 27 Sep, 14:00 IST'}].map(m=><article key={m.name}><Icon name={m.icon as IconName} size={28}/><h3>{m.name}</h3><p>{m.text}</p><span className={`pill ${m.state==='Stale'?'gold':'green'}`}>{m.state}</span></article>)}</div><div className="note-box"><Icon name="info"/><p>Stale readings remain visible but must not drive actions requiring fresh data. Real commissioning, calibration, device credentials, and telemetry ingestion are not connected.</p></div></section>}
 {view==='reports'&&<section className="panel report-method"><h2>Know what the numbers mean.</h2><div className="method-grid"><article><h3>Observations, not promises</h3><p>The downloaded CSV contains daily simulated quantities for {siteName}, {periodLabel}. These are illustrative records, not achieved environmental outcomes.</p></article><article><h3>Keep the boundaries clear</h3><p>Food waste recorded is not food waste prevented. Solar generated is not grid use avoided. Water reused is separate from water recovered.</p></article><article><h3>Carbon impact unavailable</h3><p>No approved emission factors or accounting boundaries are configured. Unavailable impact is not reported as zero.</p></article></div><button className="button button-dark" onClick={exportReport}><Icon name="download" size={17}/> Download simulated CSV</button></section>}
 {view==='notifications'&&<section className="panel"><h2>Needs a little attention</h2><div className="alert-list"><article><span className="icon-tile gold"><Icon name="sensor"/></span><div><h3>Garden soil sensor readings are stale</h3><p>Last observed 27 Sep, 14:00 IST. Check the device before planning irrigation.</p><Link href={url('hub')} className="text-link">View hub <Icon name="arrow" size={15}/></Link></div></article><article><span className="icon-tile blue"><Icon name="water"/></span><div><h3>Water quality review has expired</h3><p>The proposed reuse route is blocked until current evidence is recorded.</p><button className="text-button" onClick={()=>explainRecommendation('water-reuse')}>Review the limitation <Icon name="arrow" size={15}/></button></div></article></div><p className="read-only-note">These are fixture alerts from 28 September 2026, not live notifications. No emails or push messages are sent.</p></section>}
 <footer className="dashboard-footer"><span><Icon name="leaf" size={14}/> Every loop is a step forward.</span><span>Read-only demo · Asia/Kolkata · Human-led decisions</span></footer></main></div>
 <dialog ref={dialog} className="detail-dialog" aria-labelledby="detail-title" onCancel={e=>{e.preventDefault();closeDetail()}} onClick={e=>{if(e.target===e.currentTarget)closeDetail()}}>{detail&&<><div className="dialog-header"><p className="eyebrow">{detail.eyebrow}</p><button className="icon-button" aria-label="Close details" onClick={closeDetail}><Icon name="close"/></button></div><h2 id="detail-title">{detail.title}</h2><div className="dialog-body">{detail.body}</div><button className="button button-dark" onClick={closeDetail}>Back to workspace</button></>}</dialog></div>;
}
